d_obs_at_popup:
- 0.22370578944475894
- -0.7210122786959163
- -0.4157107029295637
- -0.2672763134126166
- -0.08786003156592814
- 0.5703519227860272
- -0.6006524356832805
- 0.02846887682722321
- 0.18482913772408494
- -0.9070991745600046
- 0.21508970380287673
- -0.6589517526254169
- -0.869896814029441
- 0.8977710745066665
- 0.9312640661491187
- 0.6167946962329223
- -0.39077246165325863
- -0.8046557719872323
- 0.3684660530243138
- -0.1196950125207974
s_ego_at_popup:
- 175.0
- 571.402484692531
- 967.8049693850619
- 1364.207454077593
- 1760.6099387701238
- 2157.0124234626546
- 2553.414908155186
- 2949.8173928477167
- 3346.2198775402476
- 3742.6223622327784
- 4139.024846925309
- 4535.4273316178405
- 4931.829816310372
- 5328.232301002902
- 5724.6347856954335
- 6121.037270387964
- 6517.439755080495
- 6913.842239773026
- 7310.244724465557
- 7706.647209158088
s_obs_at_popup:
- 189.74908023769473
- 587.3039133053508
- 983.2689572686847
- 1379.404771045987
- 1774.9219760510086
- 2171.324412503327
- 2567.5310753795225
- 2965.5497451392666
- 3361.422107563734
- 3758.0385073883704
- 4153.066015913901
- 4551.367151322164
- 4947.494701591972
- 5342.656979224259
- 5738.998435629847
- 6135.404079407671
- 6532.048239566414
- 6928.891752636291
- 7325.108614502841
- 7721.229667438484
